[package]
name = "tsnx-host"
description = "Host (macOS/Linux) driver for tsnx-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
tsnx-core = { workspace = true, features = ["std"] }
log = "0.4"
env_logger = { version = "0.11", default-features = false, features = ["auto-color", "humantime"] }
