#!/usr/bin/env python3
"""Generates crates/tsnx-core/src/tls/roots.rs: a curated subset of the
webpki-roots trust anchors (Mozilla's set), to keep the Switch build small.

Covers Tailscale (Let's Encrypt) and the CAs self-hosted control servers
commonly use. Anything else: configure the server's root with ca_cert=.
Usage: tools/gen-roots.py <path to webpki-roots/src/lib.rs>
"""
import re, sys

KEEP = ["ISRG Root", "GTS Root", "DigiCert Global Root", "USERTrust", "Amazon Root CA",
        "GlobalSign Root", "GlobalSign ECC Root", "Microsoft RSA Root", "Microsoft ECC Root"]

src = open(sys.argv[1]).read()
body = src[src.index("pub const TLS_SERVER_ROOTS"):]
entries = re.findall(r"(  /\*.*?\*/\s*TrustAnchor \{.*?\n  \},)", body, re.S)
kept_ec, kept_rsa = [], []
for e in entries:
    label = re.search(r'Label: "([^"]+)"', e).group(1)
    if any(k in label for k in KEEP):
        # Drop the PEM comment block; keep the label for readability.
        anchor = e[e.index("TrustAnchor {"):]
        spki = re.search(r'subject_public_key_info: Der::from_slice\(b"(.*?)"\)', anchor, re.S).group(1)
        is_ec = r"*\x86H\xce=\x02\x01" in spki  # id-ecPublicKey
        (kept_ec if is_ec else kept_rsa).append(f"  // {label}\n  {anchor}")
out = ["// Generated by tools/gen-roots.py from webpki-roots (Mozilla's root set).",
       "// Do not edit by hand. Curated for size; see the script for the list.",
       "use rustls::pki_types::{Der, TrustAnchor};", "",
       "/// ECDSA roots.",
       "pub const ROOTS_EC: &[TrustAnchor<'static>] = &["] + kept_ec + ["];", "",
       "/// RSA roots. Needed everywhere: Tailscale's frontends serve RSA or",
       "/// ECDSA certificates depending on which one answers.",
       "pub const ROOTS_RSA: &[TrustAnchor<'static>] = &["] + kept_rsa + ["];", ""]
open("crates/tsnx-core/src/tls/roots.rs", "w").write("\n".join(out))
names = lambda ks: ", ".join(re.search(r'// (.*)', k).group(1) for k in ks)
print(f"kept {len(kept_ec)} ECDSA roots: {names(kept_ec)}")
print(f"kept {len(kept_rsa)} RSA roots: {names(kept_rsa)}")
